### ISSUE TITLE
Cargo instead make

### ISSUE THREAD

**Issue by dumindu** [mrLSD/iron-cms#2]
Can't we use cargo instead of make somehow?

**Comment by mrLSD** [comment]
What did you mean?
Make represent only useful commands.
You can use all cargo commands as always.

**Comment by dumindu** [comment]
about readme file content

    install Rust: make install
    run: make
    build: make build
    release build: make release
    test: make test

Why suggesting make, instead using cargo?

**Comment by mrLSD** [comment]
Do you have cargo autocomplete?
I use Ubuntu, and cargo does not support command autocomplete. It's unuseful.

If you look at Makefile carefully you find more commands. For example - install Rust, docker. It's impossible install/update Rust via Cargo.

And for the end, you should clarify why Makefile exists:
https://bost.ocks.org/mike/make/
